--local lsp = require('lsp-zero').preset({})
--
--lsp.on_attach(function(client, bufnr)
--  -- see :help lsp-zero-keybindings
--  -- to learn the available actions
--  lsp.default_keymaps({buffer = bufnr})
--end)
--
--lsp.ensure_installed({'clangd', 'pyright'})
--
--lsp.setup()
--
--lsp.extend_cmp()
--local cmp = require('cmp')
--cmp.setup({
--  mapping = {
--    -- `Enter` key to confirm completion
--    ['<CR>'] = cmp.mapping.confirm({select = false}),
--
--    -- Ctrl+Space to trigger completion menu
--    ['<C-Space>'] = cmp.mapping.complete(),
--  },
--})
